arch: amd64
os: linux

language: groovy

go:
  - 1.13.5
  
jdk:
  - openjdk8

before_install:
  - export BIN_DIR="$HOME/bin" && echo $PATH
  - export PATH="$PATH:$BIN_DIR" && echo $PATH
  - sudo apt-get update
  - sudo apt-get install -y build-essential libssl-dev uuid-dev libseccomp-dev pkg-config squashfs-tools cryptsetup
  - export GO_VERSION=1.13.5 OS=linux ARCH=amd64
  - wget -qO- https://dl.google.com/go/go${GO_VERSION}.${OS}-${ARCH}.tar.gz | tar xz 
  - export PATH="$PATH:$PWD/go/bin" && echo $PATH
  - git clone https://github.com/sylabs/singularity.git && cd singularity
  - echo $(which go)
  - ./mconfig
  - cd builddir && make
  - mv $PWD/singularity $BIN_DIR
  - cd ../..

env:
  - NXF_HOME="$HOME/.nextflow"

install:
  - sudo apt-get -qq update
  - mkdir $NXF_HOME
  - wget https://github.com/nextflow-io/nextflow/releases/download/v19.10.0/nextflow-19.10.0-all
  - chmod a+x nextflow-19.10.0-all
  - mv nextflow-19.10.0-all $NXF_HOME/nextflow
  - export PATH=$PATH:$NXF_HOME

script:
  - cd metagenomics-pipelines && make test CONF=singularity_test
