language: groovy
  
jdk:
  - openjdk8

before_install:
  - wget -O- http://neuro.debian.net/lists/xenial.us-ca.libre | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
  - sudo apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9
  - sudo apt-get update
  - sudo apt-get install -y singularity-container

env:
  - NXF_HOME="$HOME/.nextflow"

install:
  - sudo apt-get -qq update
  - mkdir $NXF_HOME
  - wget https://github.com/nextflow-io/nextflow/releases/download/v19.10.0/nextflow-19.10.0-all
  - chmod a+x nextflow-19.10.0-all
  - mv nextflow-19.10.0-all $NXF_HOME/nextflow
  - export PATH=$PATH:$NXF_HOME

script:
- make test CONF=singularity_test
