arch: amd64
os: linux

language: groovy

jdk:
  - openjdk8

before_install:
  - eval "$(gimme 1.13.5)"
  - sudo apt-get update
  - sudo apt-get install -y build-essential libssl-dev uuid-dev libseccomp-dev pkg-config squashfs-tools cryptsetup
  - git clone https://github.com/sylabs/singularity.git && cd singularity
  - ./mconfig && cd builddir && make && sudo make install
  - cd ../..

env:
  - NXF_HOME="$HOME/.nextflow"
  
install:
  - sudo apt-get -qq update
  - mkdir $NXF_HOME && export PATH="$NXF_HOME:$PATH"
  - wget https://github.com/nextflow-io/nextflow/releases/download/v19.10.0/nextflow-19.10.0-all
  - chmod a+x nextflow-19.10.0-all && mv nextflow-19.10.0-all $NXF_HOME/nextflow

script:
  - cd metaflowmics && make test CONF=local_test
