arch: amd64
os: linux

language: groovy

go:
  - 1.13.5
  
jdk:
  - openjdk8

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential libssl-dev uuid-dev libseccomp-dev pkg-config squashfs-tools cryptsetup
  - export VERSION=1.13.5 OS=linux ARCH=amd64
  - wget -qO- https://dl.google.com/go/go${VERSION}.${OS}-${ARCH}.tar.gz | tar xz 
  - export PATH=${PWD}/go/bin:${PATH}
  - git clone https://github.com/sylabs/singularity.git && cd singularity
  - cd singularity && ./mconfig
  - cd builddir && make
  - export PATH=$PATH:$PWD/
  - cd ../..

env:
  - NXF_HOME="$HOME/.nextflow"

install:
  - sudo apt-get -qq update
  - mkdir $NXF_HOME
  - wget https://github.com/nextflow-io/nextflow/releases/download/v19.10.0/nextflow-19.10.0-all
  - chmod a+x nextflow-19.10.0-all
  - mv nextflow-19.10.0-all $NXF_HOME/nextflow
  - export PATH=$PATH:$NXF_HOME

script:
  - cd metagenomics-pipelines && make test CONF=singularity_test
