language: groovy
  
jdk:
  - openjdk8

before_install:
  - sudo apt-get update
  - sudo apt-get install -y singularity-container

env:
  - NXF_HOME="$HOME/.nextflow"

install:
  - sudo apt-get -qq update
  - mkdir $NXF_HOME
  - wget https://github.com/nextflow-io/nextflow/releases/download/v19.10.0/nextflow-19.10.0-all
  - chmod a+x nextflow-19.10.0-all
  - mv nextflow-19.10.0-all $NXF_HOME/nextflow
  - export PATH=$PATH:$NXF_HOME

script:
- make test CONF=singularity
