arch: amd64
os: linux

language: groovy

jdk:
  - openjdk8

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential libssl-dev uuid-dev libseccomp-dev pkg-config squashfs-tools cryptsetup
  - export GO_VERSION=1.13.5 OS=linux ARCH=amd64
  - wget -qO- https://dl.google.com/go/go${GO_VERSION}.${OS}-${ARCH}.tar.gz | tar xz
  - export PATH="$PWD/go/bin:$PATH"
  - git clone https://github.com/sylabs/singularity.git && cd singularity
  - go version
  - cat mlocal/checks/version.go
  - env GO111MODULE=off go run mlocal/checks/version.go go1.13
  - go run mlocal/checks/version.go go1.13
  - ./mconfig
  - cd builddir && make  
  - cd ../..

env:
  - NXF_HOME="$HOME/.nextflow"
  
install:
  - sudo apt-get -qq update
  - mkdir $NXF_HOME
  - wget https://github.com/nextflow-io/nextflow/releases/download/v19.10.0/nextflow-19.10.0-all
  - chmod a+x nextflow-19.10.0-all
  - mv nextflow-19.10.0-all $NXF_HOME/nextflow
  - export PATH=$PATH:$NXF_HOME

script:
  - cd metagenomics-pipelines && make test CONF=singularity_test
